language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo apt-get update -qq
  - sudo apt-get -y install libproj-dev libgdal1-dev
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r devtools
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_r RCurl
  - ./travis-tool.sh install_r XML
  - ./travis-tool.sh install_r sp
  - ./travis-tool.sh install_r rgdal
  - ./travis-tool.sh install_r rgeos
  - ./travis-tool.sh install_r uuid
  - sudo apt-get install libgeos-dev
  
script:
  - ./travis-tool.sh run_tests
  
after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
