# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libcurl4-openssl-dev

r:
  - oldrel
  - release
  #- devel
  
#r_binary_packages:
#  - RCurl
#  - XML
#  - rgdal
#  - rgeos
  
r_packages:
  - devtools
  - RCurl
  - XML
  - rgdal
  - testthat
  - sp
  - rgeos
  - uuid

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
