language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo apt-get update -qq
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal1-dev
  - sudo apt-get install libproj-dev
  - ./travis-tool.sh bootstrap
  - sudo apt-get install libgeos-dev
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
