language: c

before_install:
  - sudo apt-get update -qq
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh install_aptget libgdal1h gdal-bin libgdal1 libgdal-dev libgdal1-dev libproj-dev
  - ./travis-tool.sh bootstrap
  - sudo apt-get install libgeos-dev
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
